[phases.setup]
commands = [
    "apt-get update",
    "apt-get install -y python3-pip python3-dev build-essential"
]

[phases.install]
commands = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
cmd = "uvicorn app:app --host 0.0.0.0 --port ${PORT} --timeout-keep-alive 60"
